In [1]:
import numpy as np

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [3]:
a=np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [4]:
a.reshape(2,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
a.reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
a.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [6]:
a.reshape(6,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [8]:
a.reshape(12,1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [10]:
a.reshape(2,-1)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
a.reshape(3,-1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
a.reshape(12,-1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [16]:
a.reshape(-1,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [18]:
a.reshape(-1,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

4.Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным? Нет, масив двух мерный, см. ниже


In [22]:
a.reshape(12,1).ndim

2

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [23]:
np.random.randn(3,4)

array([[-0.51149584, -0.12070891, -0.06098158,  1.55845059],
       [ 0.69930028, -0.51593519, -0.90821672,  1.77552367],
       [ 0.54506133, -0.07115023, -0.5017886 ,  1.11497608]])

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.


In [25]:
a=np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [29]:
b=np.arange(20,1,-2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [27]:
a==b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

Нет  разнициы между a И b

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.

In [34]:
a=np.array([[0,0],
            [0,0]])
a

array([[0, 0],
       [0, 0]])

In [35]:
b=np.array([[1,1],
            [1,1],
            [1,1],
           ])
b

array([[1, 1],
       [1, 1],
       [1, 1]])

In [38]:
c=np.vstack((a,b))
c

array([[0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1]])

In [39]:
c.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [45]:
a=np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
A=a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [48]:
At=A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [51]:
B=A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [52]:
B.shape

(4, 4)

In [54]:
B.size

16

In [55]:
np.linalg.det(B)

0.0

Поскольку определитель матрицы B равен нулю, то для нее не существует обратная матрица.

10.  Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [57]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [74]:
c=np.random.randint(0,16,size=16)
c


array([10,  0,  1,  1, 11,  5,  6,  4, 15,  0,  0,  2, 13,  1,  4, 11])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [75]:
C=c.reshape((4,4))
C

array([[10,  0,  1,  1],
       [11,  5,  6,  4],
       [15,  0,  0,  2],
       [13,  1,  4, 11]])

In [77]:
D=B+C*10
D

array([[105,  14,  33,  42],
       [124, 100, 146, 162],
       [173,  86, 149, 232],
       [162, 132, 252, 412]])

In [78]:
np.linalg.det(D)

-16477999.999999981

In [80]:
np.linalg.matrix_rank(D)

4

In [86]:
D_inv=np.linalg.inv(D)
D_inv

array([[ 0.00515354, -0.00203665,  0.0081539 , -0.00431606],
       [-0.08522029, -0.00075373,  0.09276733, -0.04325404],
       [ 0.08074766,  0.02470688, -0.10559048,  0.04151232],
       [-0.02411215, -0.01406967,  0.03165675, -0.00740867]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [87]:
D_inv[D_inv>0]=1

In [88]:
D_inv[D_inv<0]=0

In [89]:
D_inv

array([[1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 1.],
       [0., 0., 1., 0.]])

In [100]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [101]:
C

array([[10,  0,  1,  1],
       [11,  5,  6,  4],
       [15,  0,  0,  2],
       [13,  1,  4, 11]])

In [99]:
E=np.where(D_inv,B,C)
E

array([[  5,   0,  23,   1],
       [ 11,   5,  86,   4],
       [ 23,  86,   0, 212],
       [ 13,   1, 212,  11]])